[package]
name = "wnp-report-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.3"
webhook = "2.1.2"
rocket = { version = "0.5.0-rc.3", features = ["json"] }
serde = "1.0.167"
